name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app
      
    - name: Run tests
      run: xcodebuild test -scheme FoodExp_Manager -project FoodExpManager/FoodExp_Manager.xcworkspace -destination 'platform=iOS Simulator,name=iPhone 14,OS=15.0'
